### ISSUE TITLE
option to show only table/chart

### ISSUE THREAD

**Issue by rheinheimer** [plotly/react-pivottable#10]
This is a feature request/suggestion: to hide all pivottable controls, keeping only the pivot table/chart, similar to in Excel. This would be simply a boolean API key with a default value of true.

I am trying to not only explore data, but also save charts for later use in a dashboard, in which case there would be no changing of aggregators, etc., yet the data would still automatically update (somewhat like in Metabase). However, the pivot functionality is still needed, even if the controls are disabled. Other options to achieve this are 1) my own CSS (which I'll do in the short term) and 2) server-side replication of the pivottable functionality to serve the pivoted data.

**Comment by nicolaskruchten** [comment]
It's actually pretty easy to do, even easier than the jQuery version: instead of using `<PivotTableUI ... />` just use `<PivotTable ... />`. The two variants accept the same parameters and the rendering is the same except that in the latter case, there no UI around it. More information is available in the ReadMe section here: https://github.com/plotly/react-pivottable#properties-and-layered-architecture

**Comment by rheinheimer** [comment]
@nicolaskruchten Thanks! Apologies for not reading the fine print. Still, I decided to bypass PivotTable entirely for the display-only part. The issue is I don't want to download so much raw data when rendering multiple charts created with PivotTableUI. My strategy is to pass a function as a PivotTableUI prop to the renderer to save the pivotted data back to the main component (the function could be anywhere in the renderer; I put it in Plotly's onAfterPlot prop, but that's probably unnecessary). I then save the pivoted data back to my database for future rendering in PivotTable-free plots/tables. Automatic updating of charts without pulling data from the server will be a challenge. I'll probably end up replicating PivotTable server-side w/ Python+Pandas. Or setup a node server...

Feel free to close - just wanted to let you know about this approach.

**Comment by nicolaskruchten** [comment]
Thanks for sharing!
