### ISSUE TITLE
React App crashes when trying to use react-plotly.js

### ISSUE THREAD

**Issue by ShreyaRijal** [plotly/react-pivottable#101]
**Hi, my app crashes when I try to execute the example code from GitHub. When I remove these imports:** 
import Plot from 'react-plotly.js';
import createPlotlyRenderers from 'react-pivottable/PlotlyRenderers';

**the application loads up fine. However when that code is included, it crashes.**

**In the terminal I pasted this command:**
npm install --save react-pivottable react-plotly.js plotly.js react react-dom

**I copied this code:**

import React from 'react';
import PivotTableUI from 'react-pivottable/PivotTableUI';
import 'react-pivottable/pivottable.css';
import TableRenderers from 'react-pivottable/TableRenderers';
import Plot from 'react-plotly.js';
import createPlotlyRenderers from 'react-pivottable/PlotlyRenderers';

// create Plotly renderers via dependency injection
const PlotlyRenderers = createPlotlyRenderers(Plot);

// see documentation for supported input formats
const data = [['attribute', 'attribute2'], ['value1', 'value2']];

class App extends React.Component {
    constructor(props) {
        super(props);
        this.state = props;
    }
    render() {
        return (
            <PivotTableUI
                data={data}
                onChange={s => this.setState(s)}
                renderers={Object.assign({}, TableRenderers,PlotlyRenderers)}
                {...this.state}
            />
        );
    }
}

//ReactDOM.render(<App />, document.body);
export default App;

**I get these issues in my terminal:**

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! test-app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the test-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**I couldn't find anyone else with the same problem**

**Thank you**

**Comment by niekbruins** [comment]
I have the same problem. The workaround for me is to use plotly external by adding it with the <script> tag

**Comment by ShreyaRijal** [comment]
How do you do that in React?

**Comment by niekbruins** [comment]
> How do you do that in React?

See https://github.com/plotly/plotly.js#use-the-plotlyjs-cdn-hosted-by-fastly

**Comment by ShreyaRijal** [comment]
For those who are curious about adding scripts into React. This is the way I did it. 

 componentDidMount() {
        const script = document.createElement("script");
        script.src = "https://cdn.plot.ly/plotly-latest.min.js";
        script.charset="utf-8";
        script.async = true;
        script.onload = () => this.scriptLoaded();

        document.body.appendChild(script);
    }

This code is in the page i want to load the pivottable.
