### ISSUE TITLE
How do I define my own color scheme for Table Heatmap?

### ISSUE THREAD

**Issue by deecay** [plotly/react-pivottable#118]
Hi,

I would like to use custom color scales in Table Heatmap, just like the Montreal Weather 2014 Dataset example for pivottable.js. How do I do this in react-pivottable?

**Comment by xhlulu** [comment]
This code snippet shows how to use the `makeRenderer` to create a renderer: https://github.com/plotly/react-pivottable/blob/33c77e9bb9a82a47f6eba4e51284ca11a603b3cd/src/TableRenderers.jsx#L347-L354

You can import `makeRenderer` from `TableRenderers` to create your own renderer, and pass it to your react-pivottable (see README for an example)

**Comment by jheckman-rt** [comment]
how do you import something that is not exported?  The makeRenderer() function needs to be exported in order to import it to customize it.

**Comment by Edweezu** [comment]
did you ever figure out how to do this @jheckman-rt  @deecay?

**Comment by nicolaskruchten** [comment]
You should be able set a `tableColorScaleGenerator` prop that returns a colorscale function.

**Comment by ScottGuthart** [comment]
Here's an example that uses [d3 scale chromatic](https://github.com/d3/d3-scale-chromatic) and the tableColorScaleGenerator prop @nicolaskruchten mentioned.

```javascript
import { interpolateRdYlGn } from "d3-scale-chromatic";


      <PivotTableUI
        data={data}
        onChange={(s) => setState(s)}
        renderers={Object.assign({}, TableRenderers, PlotlyRenderers)}
        tableColorScaleGenerator={(values) => {
          const min = Math.min.apply(Math, values);
          const max = Math.max.apply(Math, values);
          const range = max - min;
          return (x) => {
            const progress = (max - x) / range;
            const backgroundColor = interpolateRdYlGn(1 - progress)
            return { backgroundColor };
          };
        }}
        {...state}
      />

```
If you install [d3 scale chromatic](https://github.com/d3/d3-scale-chromatic) you can use any of [their color scale functions](https://github.com/d3/d3-scale-chromatic#diverging) which take a number from 0 to 1 and return a color.

If you want to roll your own, you can still follow the basic structure above. Essentially, you'll just pass a function to the tableColorScaleGenerator prop that accepts a list of values and returns another function which takes one of those values and returns a CSS-in-JS object like `{backgroundColor: myCalculatedBgColor}` with the appropriate background color for the passed value.

**Comment by deecay** [comment]
Thanks @nicolaskruchten , @ScottGuthart 

Everything clear now. The code example was super helpful. I have decided to create a different kind of lighten function to preserve the gradient in the lighter area.

```
  function lighten (color, amount) {
    const r = d3.rgb(color).r;
    const g = d3.rgb(color).g;
    const b = d3.rgb(color).b;
    const newColor = d3.rgb(
      ( r + (255 - r) * amount ),
      ( g + (255 - g) * amount ),
      ( b + (255 - b) * amount ),
    );
    return newColor.toString();
  }
```

**Comment by deepsweech** [comment]
This thread is very useful. In my case, I used d3's scaleLinear function to define the min, max and the range of colors. Example:

`
const minColor = 'white'
	const maxColor = 'blue'
	const tableColorScaleGenerator = (values) => {
		const min = Math.min.apply(Math, values);
		const max = Math.max.apply(Math, values);
		const myColor = d3
			.scaleLinear()
			.domain([min, max])
			.range([minColor, maxColor]);

		return (x) => {
			return { backgroundColor: `${myColor(x)}` };
		};
	};
`
