### ISSUE TITLE
How to make some default views?

### ISSUE THREAD

**Issue by crapthings** [plotly/react-pivottable#14]
i want to make some defaults as preset.

so user can click a link and check this view directly without dragging by themself.

like this 

https://jsfiddle.net/nicolaskruchten/kn381h7s/

**Comment by crapthings** [comment]
it looks like i can pass rows cols as props

**Comment by crapthings** [comment]
almost their

if i use aggregatorName "Sum", how to set next step ?

i want to set default "Sum Field"

but i can't figure out how to do that.

![image](https://user-images.githubusercontent.com/1147704/35672965-0b4ce858-077b-11e8-8c8d-21908acdc2d1.png)


```js
<PivotTableUI
  data={this.state.pivotData}
  rows={this.state.currentPivot.rows}
  cols={this.state.currentPivot.cols}
  aggregatorName={this.state.currentPivot.aggregator[0]}
  onChange={s => this.setState(s)}
  {...this.state}
/>
```

**Comment by nicolaskruchten** [comment]
You can pass the names of the arguments to the aggregator with the `vals` prop. So if you wanted the sum of ratings, it would be:

<PivotTableUI
  aggregatorName="Sum"
  vals={["ratings"]}
/>

**Comment by crapthings** [comment]
awesome

**Comment by crapthings** [comment]
@nicolaskruchten 

how to use table heatmap defaultly ?

**Comment by crapthings** [comment]
```js
{
  rendererName: 'Table Heatmap',
}
```
