### ISSUE TITLE
How to show only Table / Sum over a particular field.

### ISSUE THREAD

**Issue by ndroock1** [plotly/react-pivottable#19]
This react pivot table perfectly does the job for me. However, at this moment I =only= need the Table renderer which sums the values of a particular field. So I don't want to show the selectors in the top left corner and want to set its default values on beforehand. How can I do this??

**Comment by nicolaskruchten** [comment]
Glad this is working for you! To control what shows up in those dropdowns, you can provide your own values for `renderers` and `aggregators`.

**Comment by ndroock1** [comment]
Got it working, thank you, Nicolas, (Mr. Kruchten). You made an -amazing- piece of software! ( My site is not ready for the public domain yet... but will be soon, I hope. )

**Comment by nicolaskruchten** [comment]
Awesome, happy it's working for you!
