### ISSUE TITLE
Large Dataset

### ISSUE THREAD

**Issue by krazziekay** [plotly/react-pivottable#2]
Firstly, marvelous job on this Pivot table! I really like it. I have been trying to make a pivot table myself in react. And I have made a sample for a small data sample, however my main issue is how to render large data sets I am talking about thousands and yes possibly millions of data. 
The pivoting algorithm is just fine, but the rendering time is just too much when we are talking about large data set. Lets say I have a CSV file of about 30MB and I am importing data from that file. The browser just can not handle data of this size, it just crashes!!
If you are going to make this pivot table in ReactJS, please tell me is there any way or some sort of idea to render data in amounts of thousands or millions in a pivot table??

**Comment by nicolaskruchten** [comment]
Hi! Glad you're excited about this :) It's very early days for this project so I have no idea about its performance characteristics.

That said, the original PivotTable.js can handle largeish CSV files, in the 100,000-record range. PapaParse is the library I use in the examples like this one https://pivottable.js.org/examples/local.html and it handles the parsing just fine. The rendering time will depend on how many cells you want in the output table.

**Comment by krazziekay** [comment]
Ya I too used Papaparse for converting CSV into JSON. But the main issue which I faced was rendering. Well when we are talking about millions of data, obviously there will be millions of cells, and that is the problem. When we pivot data as per the fields in the rows and columns, the browser just crashes, the rendering just seems impossible.
Here is my repo, feel free to check it:
https://github.com/krazziekay/reactPivot

**Comment by nicolaskruchten** [comment]
Well, actually, millions of records shouldn't mean millions of cells, to my mind... The main utility of a pivot table is to aggregate data to make it human-readable, and humans can't parse tables with millions of cells :)

As an example, when I worked in ad-tech we had data about millions of ads that were shown, but we using PivotTable.js to produce useful human-readable tables with just a few dozen cells: for example the rows were ad sizes and columns were day or week, and the cells were click-through rates.
