### ISSUE TITLE
pivot filter box position

### ISSUE THREAD

**Issue by CraigMeng** [plotly/react-pivottable#21]
Hi,

Awesome work!

Recently in my project, I found that pivot filter box will be out of view port. Line 214, inn the file PivotTableUI.js, I saw the position is the absolute distance. However, seems that react-draggable is using relative distance from parent dom (Not sure, though)

**Comment by nicolaskruchten** [comment]
Glad you like it! Can you explain how to reproduce the behaviour you're seeing? OS, Browser, window size?

**Comment by CraigMeng** [comment]
Hi,
I can reproduce this issue together with Bootstrap.css

simple layout:
`import React, { Component } from 'react';
import DataTable from './DataTable';

class App extends Component {
  render() {
    return (
      <div className="container-fluid">
          <div className="row">
              <div className="col-md-6">
                  <DataTable/>
              </div>
              <div className="col-md-6">
                  <DataTable/>
              </div>
          </div>
      </div>
    );
  }
}

export default App;`

DataTable.js
`import React, { Component } from 'react';
import PivotTableUI from 'react-pivottable/PivotTableUI';
import 'react-pivottable/pivottable.css';
import TableRenderers from 'react-pivottable/TableRenderers';

class DataTable extends Component {
    constructor(props) {
        super(props);
        this.state = {
            data: [
                {
                    attr1: "1",
                    attr2: "2"
                },
                {
                    attr1: "3",
                    attr2: "4"
                }
            ]
        }
    }

    render() {
        return (
            <div style={{height: "450px", width: "100%", overflowY: "auto", overflowX: "auto"}}>
                <PivotTableUI
                    data={this.state.data}
                    renderers={Object.assign({}, TableRenderers)}
                    onChange={s => this.setState(s)}
                    {...this.state}
                />
            </div>
        )
    }
}

export default DataTable;`

As you can see, I put two data tables on one page, if you click the filters on second table, you would see the filter box is positioned out of the viewport. (Browser: 63.0.3239.84 (Official Build) (64-bit), screen resolution: 1900*1200)

**Comment by CraigMeng** [comment]
Hi,
I can reproduce this issue together with Bootstrap.css

![app](https://user-images.githubusercontent.com/4469305/37039533-b1aecb86-2192-11e8-9814-79dae8697c86.png)

DataTable.js:
![data](https://user-images.githubusercontent.com/4469305/37039541-bdfb3078-2192-11e8-8582-85f3527f1411.png)


As you can see, I put two data tables on one page, if you click the filters on second table, you would see the filter box is positioned out of the viewport. (Browser: 63.0.3239.84 (Official Build) (64-bit), screen resolution: 1900*1200)

**Comment by nicolaskruchten** [comment]
Does the solution proposed in https://github.com/nicolaskruchten/pivottable/issues/865 work for this issue as well?

**Comment by steventebrinke** [comment]
In our app, the pivot table is embedded in another layout and also the filter box position is off (it's too far down). The proposed solution does not change anything in our case.

**Comment by kaiatgithub** [comment]
I had the same issue (position too far down) and fixed it by removing the top- and left-attributes in PivotTableUI.jsx on line 58 and 59 ([see here](https://github.com/kaiatgithub/react-pivottable/commit/c7e67f0f342156c5a70a6191130cecb6102f2697)).

**Comment by claudio-rodriguez** [comment]
Working on moving from pivottable to react-pivottable, getting the same issue, removing top and left attributes fixes the filter position for me too!

**Comment by claudio-rodriguez** [comment]
hey, thanks for the follow up! I was able to reproduce the issue in a codesandbox: https://codesandbox.io/s/6w7x5q74nr

I reproduced something like what we have in our page, we have a left panel with some sort of list, then in the right panel we have some bootstrap tabs, a data table and then in another tab the pivottable, at first I only added the tabs and the issue wouldn't show, then, when I added the left and right panel thing the issue showed, so it is related to having the pivottable inside bootstrap columns.

![image](https://user-images.githubusercontent.com/20847960/47026996-d73d9d00-d123-11e8-86d6-b4ce83f2003f.png)

![image](https://user-images.githubusercontent.com/20847960/47027084-00f6c400-d124-11e8-9950-108cf29511ad.png)

hope this helps solving the issue!! :)

**Comment by umed48** [comment]
hi @nicolaskruchten , do you have any progress on this issue? I have the same problem and I can reproduce it using 
@claudio-rodriguez 's example.

Thanks in advance!

**Comment by nicolaskruchten** [comment]
Fixed in https://github.com/plotly/react-pivottable/releases/tag/v0.8.0
