### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by scriptobotic** [plotly/react-pivottable#24]
Hi!
There is a documentation about localization in pivottable. It's for jquery. There is no posibility to manage locale in react-pivottable. It would be great if i could do it through some props.
Thanks.

**Comment by scriptobotic** [comment]
Unfortunately, string labels were hardcoded into code. But if we use prop locale(f.e.) we could use it into pivotData.

**Comment by kfern** [comment]
Localization, including smart number formatting, is included in Initial Roadmap #1 

https://github.com/yahoo/react-intl provides React components and an API to format dates, numbers, and strings, including pluralization and handling translations.

Does anyone have experience with this library?

**Comment by nicolaskruchten** [comment]
Localization is still on the roadmap for this library but I haven't gotten around to it yet, sorry!
