### ISSUE TITLE
Display a colunm and sort with another

### ISSUE THREAD

**Issue by fabiokiatkowski** [plotly/react-pivottable#26]
First of all, great project.

I'm having an issue with the follwing image
![image](https://user-images.githubusercontent.com/1231162/38577601-c4be5646-3cd7-11e8-8946-8d82ebfd2ab3.png)

the domain rules is about size of clothes, here in Brazil we have P M G GG like S, M, L, XL. So I needed to render this sizes on right order.

I can't find any props to render on this way.

**Comment by nicolaskruchten** [comment]
You should be able to use the `sorters` prop to specify the order you want to use for the `Tamanho` attribute. You can see this in action in the demo here: https://github.com/plotly/react-pivottable/blob/master/examples/App.jsx#L44

**Comment by fabiokiatkowski** [comment]
Yes, I saw this function but I tried with the following code
My Tips is this
`["ordemProducao", "tamanho", "cor", "quantidade", "ordenacaoTamanho"],
  [225185,"G","000001",30,95],
  [225185,"M","000001",20,90],
  [225185,"GG","000001",40,100],
  [225185,"P","000001",60,85],
  [225185,"XG","000001",50,411]`

My State is
`
this.setState({
            mode: "demo",
            filename: "Sample Dataset: Tips",
            pivotState: {
                data: tips,
                rows: ["cor"], cols: ["tamanho"],
                aggregatorName: "Integer Sum", vals: ["quantidade"],
                rendererName: "table",
                sorters: {
                    "Size": sortAs(tips.slice(1).map(tip => tip[4]).sort((a, b) => a > b))},
                plotlyOptions: {width: 900, height: 500}
            }
        });
`
I didn't get the expected behavor (behavor that I expected).

I forked and did some change, passing an object to columns attribute.

**Comment by fabiokiatkowski** [comment]
ok, I get it. thanks.
