### ISSUE TITLE
Editing plotly plots and callback

### ISSUE THREAD

**Issue by steventebrinke** [plotly/react-pivottable#32]
When editing is enabled for plotly plots, it is, for example, possible to edit the title of the plot. I'd like to use this feature, but how can I receive the new title through a callback to allow me to save the user input? As far as I can see, plotly has a callback `onUpdate`, but I do not know how to use it when the plotly plot is created through a `PivotTableUI`.

**Comment by nicolaskruchten** [comment]
Good question! At the moment all you can do once you've edited the plot is to save it to PNG or export it to Plotly Cloud using the buttons in the modebar. If you want to submit a PR that hooks up a callback so that you could receive update events, I'd likely accept it :)
