### ISSUE TITLE
New Integration: react-pivottable or pivottable.js version?

### ISSUE THREAD

**Issue by geebeetoo** [plotly/react-pivottable#37]
I love this. Thank you.

We are trying to decide if it will address our users needs.

We're on a PHP, MySQL, Javascript (jQuery) platform.

1) Should we go with react? or the regular javascript version?

2) And, some tables from which users will run visualizations will have millions of rows. I am not sure if this is even conceivable/applicable to a pivot style table, but can pagination be added to control how many rows are viewed?

Thank you
Gilles

**Comment by nicolaskruchten** [comment]
1. That's entirely your call, but the non-react version is jQuery-based so there's likely less to learn for you there...

2. Both of these libraries top out around 100k rows and have no pagination. To be honest, it basically never makes sense to generate output with more than a few thousand rows, even with pagination: who is going to scroll through that and read it all? :)

**Comment by geebeetoo** [comment]
Thank you for your quick response.

With regard to the 100K rows limit - I agree with you. I wanted to know 2 things with that question:
a) can the underlying table being queried contain more than 100K or rows?

b) Can we limit the display to x number of rows per page? for instance, 25 records per page, and have  the user click "next" or "prev" to see more?

**Comment by nicolaskruchten** [comment]
a) no 
b) no 

:)
