### ISSUE TITLE
Dash Component Support

### ISSUE THREAD

**Issue by bewernick** [plotly/react-pivottable#41]
Is getting a dash component still on the roadmap?

**Comment by bewernick** [comment]
Read only component.

**Comment by nicolaskruchten** [comment]
Would you be interested in building such a component? It's getting ever-easier to do so :) 

https://dash.plot.ly/plugins is the 'old' way and https://github.com/plotly/dash-component-boilerplate/pull/1 is the 'new' way although both work!

**Comment by bewernick** [comment]
Yeah, I’ll take a look and submit a pull request when I’m done.

**Comment by popohoma** [comment]
Hi Bewernick, have you figured out how to use react pivot table in python dash framework ?

**Comment by nicolaskruchten** [comment]
cross-posting my answer from https://github.com/nicolaskruchten/pivottable/issues/1084

It's definitely in my plans to wrap the sibling project to this one, `react-pivottable`, so as to make it accessible from Dash, but I haven't found the time recently and likely won't in the coming weeks.

That said, it's actually pretty easy to do: the process is well-documented here https://dash.plot.ly/plugins

My plan has been to add a `PivotTable` Dash component to our `dash-extra-components` library here https://github.com/plotly/dash-extra-components so if you felt like doing it and submitting it as a PR, someone from our Dash team might be able to give you a hand, and it would likely be maintained by us moving forward :)

**Comment by nicolaskruchten** [comment]
looks like one of Plotly’s superstar interns got motivated to do this :)

https://community.plot.ly/t/show-and-tell-dash-pivottable/20112
