### ISSUE TITLE
Styling bar chart

### ISSUE THREAD

**Issue by profilike** [plotly/react-pivottable#42]
Hello! Is it possible to add custom colors in Bar chart like this example https://pivottable.js.org/examples/c3.html?

**Comment by nicolaskruchten** [comment]
This version of the pivot table only supports Plotly (given that it's a Plotly-sponsored project :) so we won't be adding support for C3 for sure. That said, you can control the colors through Plotly's `colorway` attribute, although you can't associate the colors to individual keys/names at this time unfortunately. https://plot.ly/javascript/reference/#layout-colorway

**Comment by profilike** [comment]
thanks for the answer. I will try to use colorway attribute

**Comment by rawandhawez** [comment]
3 years later 

In case if anyone wondering, below worked for me:
`
rendererOptions :{
    plotly :{
        colorway  : ['#2ca070', '#d62728', '#e0cc12', '#80e012'],
    }
},`
