### ISSUE TITLE
Is React-PivotTable Free to use like PivotTable?

### ISSUE THREAD

**Issue by FaheemAnsariReal** [plotly/react-pivottable#45]
Hi Nicolas,

I would like to know that likewise pivottable, is react-pivottble is free to  use.

I'm bit confused as I've gone through plotly website and they have pricing structure also they have made the libraries open source as well. Please let me know is react-pivottable is fully free or first I've to buy plotly?

Thanks

**Comment by nicolaskruchten** [comment]
Both react-pivottable and PivotTable.js are both MIT-licensed and therefore totally free:

* https://github.com/plotly/react-pivottable/blob/master/LICENSE
* https://github.com/nicolaskruchten/pivottable/blob/master/LICENSE.md
