### ISSUE TITLE
Performance issue building from Github versus react-pivottable.js.org

### ISSUE THREAD

**Issue by rpagliuca** [plotly/react-pivottable#48]
Hi, guys.

I've noticed a huge difference in performance between the component deployed to https://react-pivottable.js.org/bundle.js in comparison to the bundle.js file that I've just build from the latest commit of master (aaff40f37d9d8623624d6040c853d310f6c6b53b).

Do you know which commit is https://react-pivottable.js.org/bundle.js was built from?

Also, I tried using git bisect to explore this issue, but I'm not that experienced with bisect, and I actually got the impression that all commits from this github repository are slower in parsing CSV files than the one I linked above.

I'm uploading a sample CSV file, that loads instantaneously on https://react-pivottable.js.org, but freezes when I try the version from Github (stays forever, with CPU usage, in "Parsing CSV..." step)

Thank you for your time and assistance.

[sample.csv.zip](https://github.com/plotly/react-pivottable/files/2361096/sample.csv.zip)

**Comment by nicolaskruchten** [comment]
The `gh-pages` branch was last updated within minutes of the latest commit, so it's very good bet they're the same. I'm not sure what would explain a performance slowdown... Perhaps one of the dependencies has changed versions? What's the diff on the bundle like?

**Comment by rpagliuca** [comment]
After building locally with `node_modules/webpack/bin/webpack.js -p` I get a fairly different bundle.js file, which is noticeable even by the different filesize (local file has 496KB, while remote file has 426KB). I tried to diff both files, but due to the nature of minified files, the output I get is useless (the whole file).

Anyways, thanks for the information though. You are probably right, there must be some difference in the dependencies.

I'll try to investigate the problem, and I'll tell you if I find something out.

**Comment by rpagliuca** [comment]
I've just updated node and npm using nvm, and now, after running npx webpack -p, everything is as fast as it should. Thanks for your help.
