### ISSUE TITLE
Using this in R Shiny

### ISSUE THREAD

**Issue by temiwale88** [plotly/react-pivottable#49]
Hello Nicholas,

This is Elijah and would like to know if this can be used within R Shiny? I'm new to coding and web dev but would certainly like to incorporate this or at least understand how it works in a viz web app. Thanks!

**Comment by nicolaskruchten** [comment]
This `react-pivottable` package cannot easily be used from Shiny, but its predecessor `PivotTable.js` has an R binding here: https://cran.r-project.org/web/packages/rpivotTable/index.html

**Comment by temiwale88** [comment]
Noted. Thanks Nicholas. I was also thinking that as part of Plotly's react component it could be easily used via R. Thanks!
