### ISSUE TITLE
How to remove the top and side part UI's ?

### ISSUE THREAD

**Issue by Yaswanth-C** [plotly/react-pivottable#50]
Hi Guys,

I want to know how can i silent the side parts of UI's means i had plotted a graph based on my data , now i want to only show the graph and for that i need to remove the UI's at the sides.

Is there any parameter for doing that ?

Thanks

**Comment by nicolaskruchten** [comment]
There is no parameter for doing that but as per the [docs](https://github.com/plotly/react-pivottable#properties-and-layered-architecture), `<PivotTableUI>` and `<PivotTable>` have the same API so you can swap one out for the other any time :)

**Comment by Yaswanth-C** [comment]
Thanks @nicolaskruchten  for responding. 

Actually this is how my `render` method look like

```
render() {
        return (
            <PivotTableUI
                data={data}
                onChange={s => this.setState(s)}
                renderers={Object.assign({}, TableRenderers, PlotlyRenderers)}
                {...this.state}
            />
        );
    }
```

You mean if i am using both `<PivotTableUI>` and `<PivotTableUI>` , it is better to use one since both have the same API . That is what you mean ?

**Comment by nicolaskruchten** [comment]
I'm saying that you can use `<PivotTableUI>` if you want the UI, and `<PivotTable>` if you don't... they take the same inputs.
