### ISSUE TITLE
Need help on how to use of plotlyOptions and plotlyConfig?

### ISSUE THREAD

**Issue by ganesh-sankey** [plotly/react-pivottable#63]
I need example to apply style to react-pivottable using plotlyOptions and plotlyConfig.
I didnt find any examples to apply styling to react-pivottable. basically i want set specific color to the border of table, font-family, background color, dropdown css etc.

```
<PivotTable
      data={this.state.data}
      plotlyOptions={{ }}
      plotlyConfig={{ }}
/>
```

What values should be passed in above component for plotlyOptions and plotlyConfig? any examples with possible options and values.

**Comment by nicolaskruchten** [comment]
To style the table, you can just use CSS, rather than any React props.

**Comment by ganesh-sankey** [comment]
> To style the table, you can just use CSS, rather than any React props.

Thnks @nicolaskruchten .
You mean that I will need to add/overwrite css for table. Also just want to know that we can do the same for filter menus(dropdowns) for applying style right? (I guess it should be same)

**Comment by nicolaskruchten** [comment]
Everything is styled with CSS so you should be able to override whatever you need.
