### ISSUE TITLE
[Feature request] Add support for specifying max-width of component

### ISSUE THREAD

**Issue by richerlariviere-lightspeed** [plotly/react-pivottable#7]
I'd like to fix this issue where the pivot table seems to be overflowing on the right of the app layout (using React Bootstrap and react 15.6.2). It seems the size of the component depends on the graph rendering. Is there a way to constraints this react component a bit more like scaling the graph rendering?

Thanks for your amazing work on this project btw. I really appreciate that. 

<img width="1273" alt="screen shot 2017-12-06 at 11 08 50 am" src="https://user-images.githubusercontent.com/31416758/33671742-756ffd10-da76-11e7-88ef-d0edccba2b70.png">

**Comment by nicolaskruchten** [comment]
I'm glad you like this component!

You're right that the size of the component basically depends on the size of the rendering, but there are a couple of ways to control that.

* For the table renderer, you can set the render area size with an overflow parameter.
* For the chart renderers, you can pass `width` and `height` options directly to Plotly via the `plotlyOptions ` prop (which is mapped to Plotly's `layout` parameter) to constrain the size of the chart to be less than the render area dimensions.

This will effectively constrain your component's size. It would be challenging to add a general-purpose max-width parameter at this point, given the varieties of ways renderers could display themselves :)

**Comment by richerlariviere-lightspeed** [comment]
Wow thanks for your fast answer!

I'll try what you suggested this afternoon. And yeah, that'd be very cool to have a general-purpose max-width parameter as you said :)

**Comment by richerlariviere-lightspeed** [comment]
For those who have the same problem, I'll post how I managed to specify the width of my renderers:

For `TableRenderer`, I added 2 CSS rules: `max-width: 500px` and `overflow: hidden` to `table.pvtTable` selector.

For `ChartRenderer`, I added a `plotlyOptions` to component declaration: 
```jsx
render() {
    const pivotTableProps = {
        data: data,
        onChange: s => this.setState(s),
        renderers: Object.assign({}, TableRenderers, plotlyRenderer),
        plotlyOptions: { width: 500} // <- Added
    }; 

    return (<PivotTableUI { ...pivotTableProps } { ...this.state } />);
}
```

Again, thank you for your help @nicolaskruchten.

**Comment by nicolaskruchten** [comment]
Thanks for sharing your solution! Please let me know if you have any other issues or questions with this library... It's newly-released so I'm hungry for feedback and eager to help!

**Comment by richerlariviere-lightspeed** [comment]
I think we can close this issue now.
