### ISSUE TITLE
About Table cell selection

### ISSUE THREAD

**Issue by TRUEJASONFANS** [plotly/react-pivottable#84]
Hi guys,
I have 2 requirement for table cell selection:

1. Table cells only support single selection.
2. When a cell is selected, the rest of cells are grayed out.  
Can the pivot table support these feature or can be support by customization?
Thanks,
Jason

**Comment by nicolaskruchten** [comment]
There aren’t any feature to do this at the moment, so you would have to clone and modify the table renderer component to do this.

**Comment by TRUEJASONFANS** [comment]
@nicolaskruchten ,
Thanks for you info.
