### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by tarekrached** [plotly/react-pivottable#95]
Hey Plotly folks!  This is an amazing project, thank you so much for releasing it!

I'm curious about your plans for this repo - as of today, February 10, it's been 8 months since the last commit (c9b6ab66786cf0e6ccf382fb2576d8e1c1434e4d `Create FUNDING.yml`)  and over 15 months since the last substantive commit (e708ab45a53496c138dc646163ae9e10647a3155 on Nov 3, 2018).

In its current state, react-pivottable generates `componentWillMount` and `componentWillUpdate` warnings when used with current (16.x) React, and will probably not work with React 17.x when that drops.

There are three open dependabot PRs that are 4 months old at this point, which makes me wonder if the project owner is looking at the project.

I guess what I'm asking is: is this project abandoned?  What can we do to support it?  If I invest time in PRs to address the React warnings, are there folks at Plotly who will review them?

Thanks again - I do not take any of the work in this repo for granted, and really do appreciate what you have built.  I would love to see it flourish.

**Comment by qweluke** [comment]
bump, I am also interested

**Comment by aboulang** [comment]
Same thought I have as I was deciding on using this vs the one used in Perspective (https://perspective.finos.org/).  Also, it looks like pivottable.js that it is based on has enhancements that have not been updated in this package.

**Comment by nicolaskruchten** [comment]
This project generally works great as-is and no one is really reporting bugs on it. The dependabot PRs didn't seem too urgent so I haven't looked at them. So the answer is... it's not dead, just doesn't seem like much work is needed.

If people want to propose changes and after discussion make some easy to review PRs, I'm happy to review them, merge them and release to NPM etc.

**Comment by tarekrached** [comment]
Right on, that sounds great - I totally agree that it's works great as-is, with the exception of the the deprecated `componentWillMount` and `componentWillUpdate` warnings.  I'll try and make a PR in the next few weeks for that.  Again, we really appreciate you putting this out into the world!

**Comment by nicolaskruchten** [comment]
Great!

With respect to the older-sibling project https://github.com/nicolaskruchten/pivottable I think the biggest thing missing is localization in this React version, and possible a few other odds and ends but I can't recall just now.

**Comment by nicolaskruchten** [comment]
> it looks like pivottable.js that it is based on has enhancements that have not been updated in this package

Just to be clear here: almost no development has happened in PivotTable.js since react-pivottable was released (both are quite mature now) so it's not the case that new stuff was added in one and not the other. Most likely I just didn't correctly port certain features when I built out react-pivottable :)

**Comment by aboulang** [comment]
Nicholas, 

Nicolas,

Not an issue with new stuff, but was the PivotTable.js community providing bug fixes to PivotTable.js after react-pivottable was released? I assume that if both still have active communities, there could be some bug fixes that you would have had to apply to both?

**Comment by nicolaskruchten** [comment]
Definitely still active, just merged @tarekrached's PR and released 0.10.0 :)
