### ISSUE TITLE
RE: Great!

### ISSUE THREAD

**Issue by aboulang** [plotly/react-pivottable#96]
Great!

With respect to the older-sibling project https://github.com/nicolaskruchten/pivottable I think the biggest thing missing is localization in this React version, and possible a few other odds and ends but I can't recall just now.

_Originally posted by @nicolaskruchten in https://github.com/plotly/react-pivottable/issues/95#issuecomment-587595788_

**Comment by aboulang** [comment]
Nicolas,

See #94 for a bug in react-pivottable that works in  pivottable.js. Also, how does on add an extension like Subtotal.js to react-pivottable?

**Comment by nicolaskruchten** [comment]
OK, thanks!

Subtotal.js is a third-party project that's not maintained by me and is incompatible with react-pivottable, as it's not react-based... Basically you'd need to write a new renderer for react-pivottable that does this subtotal stuff. 

There is an open PR here https://github.com/plotly/react-pivottable/pull/79 but it's too hard to review as-is and I've asked for it to be broken up into smaller, easier-to-merge pieces but I've gotten no uptake on that.
